#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

FILE=$1

# exit if there are no changes
git diff --cached --exit-code > /dev/null 2>&1
if [ $? -eq 0 ]; then
    exit 0
fi

# Exit if there's no commit (probably due to git commit -m)
if [ ! -f /tmp/git-diff.tmp -o ! -f /tmp/paradigm.bad ]; then
    rm /tmp/paradigm.good
    rm /tmp/paradigm.bad
    rm /tmp/git-diff.tmp
    exit 0
fi

#remove all comment lines
cat $FILE | sed '/^#/ d' > /tmp/paradigm.good

# if /tmp/paradigm.good is empty, exit
if awk 'NF {exit 1}' /tmp/paradigm.good; then
    rm /tmp/paradigm.good
    rm /tmp/paradigm.bad
    rm /tmp/git-diff.tmp
    exit 0
fi

python3 $(dirname $0)/gigaprompt.py label \
    /tmp/git-diff.tmp \
    /tmp/paradigm.good \
    /tmp/paradigm.bad
rm /tmp/paradigm.good
rm /tmp/paradigm.bad
rm /tmp/git-diff.tmp
