#!/bin/sh

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

# Only prepare commit messages for `git commit`
if [ ! -z "$COMMIT_SOURCE" ]; then
    exit 0
fi

git diff --cached > /tmp/git-diff.tmp
$(dirname $0)/gigaprompt.py complete /tmp/git-diff.tmp > /tmp/paradigm.bad
(cat /tmp/paradigm.bad; cat /tmp/git-diff.tmp | sed 's/^/#/' ) > $COMMIT_MSG_FILE

